### ISSUE TITLE
Generate landing page for hypper.io

### ISSUE THREAD

**Issue by Itxaka** [rancher-sandbox/hypper#121]
Something similar to kubewarden.io would be good enough

**Comment by Itxaka** [comment]
created under https://github.com/rancher-sandbox/hypper.io it auto publishes the static page to https://rancher-sandbox.github.io/hypper.io/

Currently buttons are in "hypper" red, which means they are in the same tone as the hypper red log but we could change that to anything

**Comment by kkaempf** [comment]
Just for reference, documentation on setting up TLS with github projects: https://confluence.suse.com/display/~ereslibre/Setting+up+TLS+with+Github+projects
