### ISSUE TITLE
Generate public docs

### ISSUE THREAD

**Issue by Itxaka** [rancher-sandbox/hypper#122]
Currently the docs reside under hypper in the docs directory but they are raw md files, not rendered nor published.

Publish them somehow to be able to link them from hypper.io

**Comment by Itxaka** [comment]
Current PR to publish the docs under github-pages as a book with the help of mdBook  https://github.com/rancher-sandbox/hypper/pull/119

**Comment by viccuad** [comment]
Do we want to run `hypper docs` and publish those as well?
If not, I suppose this card is done.

**Comment by Itxaka** [comment]
Not needed anymore, docs are still being published but they are not needed now
