### ISSUE TITLE
List instances of charts

### ISSUE THREAD

**Issue by mattfarina** [rancher-sandbox/hypper#19]
As a hypper user, I list the instances of installed charts I have access to in the current namespace, a declared namespace, or all namespaces I have access to.

The default output should be a table while output formats of JSON and YAML should be supported. JSON and YAML will enable users to script interactions more easily.

**Comment by viccuad** [comment]
Blocked and waiting for comments on https://github.com/mattfarina/log-go/issues/16, as Logger doesn't implement Writer.
