### ISSUE TITLE
Pass down helm flags

### ISSUE THREAD

**Issue by dragonchaser** [rancher-sandbox/hypper#20]
Create an additional cli parameter to pass down flags to the helm client used inside hypper.

**Example:**

```
$> hypper --debug --no-emojis install chartname some/chart --with-helm-flags="--here --we --pass --some --helm --flags"
```

**Comment by Itxaka** [comment]
Helm flags should be our flags unless Im wrong and we are gonna be hiding helm commands under our commands?

**Comment by dragonchaser** [comment]
I think this has become obsolete when we started using go composition for implementing the necessary helm commands.
