### ISSUE TITLE
Create User Docs - Tutorials/get-started

### ISSUE THREAD

**Issue by mattfarina** [rancher-sandbox/hypper#61]
Following https://documentation.divio.com/tutorials/, add Hypper tutorials that tells end-users how to:

- [ ] Install Hypper
- [x] Use Hypper to install, upgrade, and otherwise work with charts
...

**Comment by Itxaka** [comment]
Should we:
 - Copy Helm docs and expand on those with Hypper specifics
 or
 - Write specific Hypper docs and point to Helm docs for the generic stuff

**Comment by kkaempf** [comment]
imho, Hypper should stay an extension on top of Helm and be a full replacement. Cluster operators shouldn't need to think about "do I need Hypper for this or Helm ?" but always use Hypper. That said, I'd prefer the "write specific Hypper docs" option.

**Comment by viccuad** [comment]
Edited the issue and split it into "Tutorials" and "Explanations", and added issues for "How-tos" and "Reference guide".

**Comment by Itxaka** [comment]
Part of this was already done by @viccuad on https://github.com/rancher-sandbox/hypper/pull/86

So only the install part is needed now :)
