### ISSUE TITLE
Deterministic release name generation

### ISSUE THREAD

**Issue by mattfarina** [rancher-sandbox/hypper#62]
In the current setup the release name is either specified, pulled from the chart metadata, or generated when a flag is passed in. Darren suggested automatically generating a release name in a deterministic manner when a release name is not specified.

**Comment by dragonchaser** [comment]
What exactly do you have in mind? Like one of those random-three-noun name generators jitsi uses or the chart file name appended with a random n-digit numeral?

**Comment by kkaempf** [comment]
This looks easy and relieves users from naming things. Adding mvp label :wink:

**Comment by viccuad** [comment]
Right now when one does `hypper install --generate-name`, we create a name as `chart + current time`, just like Helm does (see https://github.com/rancher-sandbox/hypper/blob/main/pkg/action/install.go#L126-L139).

We could create a name as `chart + uri/repo`, `chart + sha(uri/repo)`, or something similar. Or use the `sha(uri + chartname)` to then obtain one of those cute 2-words names as docker does.

**Comment by mattfarina** [comment]
Helm v2 used to do something similar to moby by leveraging https://github.com/technosophos/moniker. If I understand the moby code right, it's random rather than deterministic. The ask is for a deterministic rather than random solution. That way I could install the chart 5 times and get the same name every time.

**Comment by dragonchaser** [comment]
Right, so if I understand it right we have to generate the names once (for each chart) and have to store it somewhere. Next question is, should it be deterministic per hypper client (would result us in storing those names in a map in the hypper cache) or should it be deterministic and identical for every cluster admin (would result in implementing a storage for that on the cluster).

**Comment by viccuad** [comment]
if it is deterministic, one doesn't need to save the release name. To obtain a release name that corresponds to that chart (+ repo url), one just calls the same function to compute the name.
If we add cluster information to the name creation, then, the names will be only deterministic inside that cluster, but there wouldn't be any need to save the name in a different cache or db.

**Comment by dragonchaser** [comment]
I am not sure if I am following you here, can you give me an example for what the name would look like for a chart named `my-awesome-chart.tar.gz` for example?

**Comment by viccuad** [comment]
let's say that you are installing `my-awesome-chart.tar.gz` from the chartpath `~/downloads/my-local-repo`. The name would be something computed from `name(my-awesome-chart, hash512sum(~/downloads/my-local-repo`))`, returning something like `my-awesome-chart-aefd52365g`.

If the chart being installed were `my-other-awesome-chart` from repo `https://my-repo.com`, the name would be computed from `name(my-other-awesome-chart, hash512sum(https://my-repo.com`))`. Returning `my-other-awesome-chart-fgfh989h` always, for example, regardless of cluster, or hypper client, because a hash function is deterministic.

**Comment by dragonchaser** [comment]
Sounds reasonable, but this will only work if there are no changes to the local repo. If you manipulate the `Chart.yml` this will change the hash and make this no long deterministic. Question is if a minor change to the local chart should change the deployment name.

**Comment by mattfarina** [comment]
To be a deterministic name, wouldn't we need to generate the same name ever time even across clusters. We're looking for the case of installing the same chart into many different clusters and always getting the same name.

To make things more complicated, we may not have a cache to pull a name from. So, we would need to be able to generate it fresh each time.

**Comment by dragonchaser** [comment]
can't we do something like `name('my-awesome-chart', hash512('hash(file)name'+'source-repo-name')`? That would not include the checksum over the filename (so changes inside the chart.yaml would still be valid) and it would be deterministic across clusters. Though this might have security implications (e.g. not being able to verify the checksum of the original chart file).

**Comment by mattfarina** [comment]
> can't we do something like `name('my-awesome-chart', hash512('hash(file)name'+'source-repo-name')`?

Two thoughts come to mind...

1. We often don't have a `'source-repo-name'`. For example, in my testing I just have the fleet chart as an archive on my file system.
2. How does a hash work when you have to do an upgrade and determine the release name to upgrade? The hash will no longer match.

We name just want to use something like the chart name as the release name.

**Comment by dragonchaser** [comment]
If we do that we assume that every repo will deliver the same chart under the same name....

**Comment by mattfarina** [comment]
> If we do that we assume that every repo will deliver the same chart under the same name....

Maybe we should list what deterministic release generation is not so we can narrow the scope:

- Name generation is not a way method to remove passing a name to hypper. It provides a default when one is not specified through an existing means
- It does not handle the case where the chart changes names and you want to upgrade across the name change
- Does not need to work in relation to a known repository (i.e., it will work with directories or chart archives locally)

Does this help?

**Comment by dragonchaser** [comment]
Yes that helps so my suggestion would a slight derivation from @viccuad proposal to use the filename and a hash over the downloaded or local chart tarball, resulting in `name('my-awesome-chart' + '-' + hash512('/path/to/downloaded/or/local/tarball')` Is this acceptable?

**Comment by viccuad** [comment]
> Sounds reasonable, but this will only work if there are no changes to the local repo. If you manipulate the `Chart.yml` this will change the hash and make this no long deterministic. Question is if a minor change to the local chart should change the deployment name.

If one changes the Chart.yaml, or makes a change to the local chart, then by definition it's a new chart, which should get it's own unique name.

**Comment by dragonchaser** [comment]
This would be solved by my last proposal, because it will always generate the name using the hash of the actual used tarball file.

**Comment by mattfarina** [comment]
@dragonchaser If you have a hash of the tarball, how will upgrade work and detect the right name to use? The upgraded chart will have a different hash. The deterministic name needs to work across upgrade.

**Comment by dragonchaser** [comment]
@mattfarina should the `--generate-name` flag be dropped or kept as it is atm? IMHO this does not make sense any more since we default to the chart name.
