### ISSUE TITLE
helm install option `--values` not recognized

### ISSUE THREAD

**Issue by kkaempf** [rancher-sandbox/hypper#68]
I'm trying to use hypper as a drop-in replacement for helm.

This helm command works:

> &gt; helm install chimera-controller chimera/chimera-controller --values custom-values.yaml

Replacing `helm` with `hypper` it doesn't work:

> &gt; hypper install chimera-controller chimera/chimera-controller --values custom-values.yaml
Error: unknown flag: --values

**Comment by Itxaka** [comment]
We are missing some flags, I noticed this while calling `install` from the upgrade, let me do a quick PR

**Comment by kkaempf** [comment]
fix confirmed. Thanks !
