### ISSUE TITLE
Fix name and namespace setting deduplication

### ISSUE THREAD

**Issue by Itxaka** [rancher-sandbox/hypper#70]
In both the install and upgrade commands we need to add a function `Name()` to calculate the name based of the annotations.

Lets try to minimize duplicates and consolidate those generic functions that are more general into one place. Also we avoid fixing bugs in 2 places!

**Comment by viccuad** [comment]
The same will be true for dealing with Namespace logic and annotations. There's https://github.com/rancher-sandbox/hypper/blob/main/pkg/action/install.go#L71-L80, and I will need to repeat that in another action, SharedDependency.
