### ISSUE TITLE
hypper upgrade not using namespace from annotations

### ISSUE THREAD

**Issue by mattfarina** [rancher-sandbox/hypper#73]
My test setup is with the fleet chart. Here's an example of how to get it...

```sh
$ wget https://github.com/rancher/charts/raw/dev-v2.5/released/assets/fleet/fleet-0.3.000.tgz
```

Then I use hypper to install the chart...

```sh
$ kubectl create ns fleet-system
$ hypper install fleet-0.3.000.tgz
```

After this you can see the release name is fleet and the resource were installed into the fleet-system namespace.

Then do an upgrade...

```sh
$ hypper upgrade fleet-0.3.000.tgz
```

This caused the revision to increment from 1 to 2 for the release. But, the upgraded resources are now in the current namespace and the original resources are still in the fleet-system namespace. If you uninstall fleet one set of resources is left behind, too.

The namespace from the annotations should be used on upgrade, too.

**Comment by Itxaka** [comment]
:+1 :+1: Can confirm. I had a comit for this but I probbly trashed by rebasing...
