### ISSUE TITLE
Add missing License and Copyright headers

### ISSUE THREAD

**Issue by dragonchaser** [rancher-sandbox/hypper#8]
Add license headers to all files/fix them up with the correct template.

**Comment by dragonchaser** [comment]
@mattfarina we need some directions here, should we go with a standard apache license header or some suse specific thing?

**Comment by kkaempf** [comment]
For license, we should choose a standard one (Apache, GPL, ...). For copyright, we need to use the standard SUSE copyright line.

**Comment by kkaempf** [comment]
https://opensource.suse.com/suse-open-source-policy.html gives some directions, esp. about copyright:

> Copyright
> 
> The code you contribute upstream or publish as Open Source as part of your job at SUSE in your work time is copyrighted or
> otherwise owned by SUSE. Use “SUSE LLC” when attributing the copyright. Use your “@suse.com” email address for
> contributions.
