### ISSUE TITLE
Shared Dependency Version Handling

### ISSUE THREAD

**Issue by mattfarina** [rancher-sandbox/hypper#90]
Shared dependencies (#30) and versions can be problematic. All of shared dependencies and their versions need to resolve across the cluster.

Some thoughts:
- We need to assume the user has access to all relevant namespaces
- We need to assume the user can install/upgrade CRDs (we are already making this assumption)
- It would be nice to have this work out in a performant manner (consider all the secrets that we will need to look through if there are many Helm charts installed)
- How we work out the version will be important. We should suggest a syntax and then look for it on lint. For example, do we want to have a range specified or an individual version and make assumptions? I would suggest we push for ranges (e.g., `^1.2.3`)

**Comment by kkaempf** [comment]
@mattfarina where can I find more information about the caret (`^1.2.3`) syntax ?


Here's [another possible approach](https://guides.rubygems.org/patterns/#declaring-dependencies) on declaring dependencies, esp. the [twiddle-wakka](https://thoughtbot.com/blog/rubys-pessimistic-operator) is useful :wink:

**Comment by viccuad** [comment]
This means that we would not to expand the Release type to save the installed chart version, correct? (I can't find any other way).

**Comment by viccuad** [comment]
@kkaempf I think the semver ranges are this ones https://devhints.io/semver (Helm uses those).

**Comment by kkaempf** [comment]
Thanks, the https://devhints.io/semver link is really helpful !
