### ISSUE TITLE
Example Repository

### ISSUE THREAD

**Issue by mattfarina** [rancher-sandbox/hypper#92]
We need a repository that contains all of the features Hypper supports as an example. This can either be:

1. A rancher charts repository that has been modified to handle shared dependencies
2. A repository of our own with a small set of charts as an example

**Comment by mattfarina** [comment]
From the planning meeting and Darren's suggestion:

- We should take the rancher repository (https://github.com/rancher/charts and dev-2.5 branch) and fork it.
- Add our annotations for dependencies.
- Build and update the index
- Only need the latest version of each chart

This will let us test it all out with the current rancher charts. This can be used as the example and for docs.

**Comment by Itxaka** [comment]
for publishing/testing how about github pages? I did a small test and it seems perfectly capable of doing so.

**Comment by Itxaka** [comment]
forked and renamed to https://github.com/rancher-sandbox/hypper-charts/ as to not collide with a possible `charts` dir on the same namespace (who knows)

Are we supposed to keep this in sync with upstream while adding our annotations? Seems like a recipe for frustration if we start encountering merge issues.....

Seems more sensible to either have our own repo with hypper only features + hypper and some rancher features and test and grown that. Otherwise we need to play catch up all the time...

**Comment by Itxaka** [comment]
Also as I understand for know we are tracking the 2.5 dev branch so that its the one that needs to be modified?


I still dont understand why we should link and depend on the rancher featureset that we *dont* support yet. For now we support name, namespace and dependencies (almost) so why should we test all the rancher custom features???

**Comment by Itxaka** [comment]
I removed the fork until this is more clear to me, it doesnt make much sense to have the current roadmap for this feature without a more clear vision or explanation about *what* we want to do with this.

**Comment by mattfarina** [comment]
To answer some questions...

> Are we supposed to keep this in sync with upstream while adding our annotations? Seems like a recipe for frustration if we start encountering merge issues.....

We don't need to worry about keeping up with the upstream location. If Hypper takes off the upstream will change to support our mild differences. Right not, this is for examples to highlight how to use Hypper and to make getting started easy.

Just make something that works as a good example.

> Also as I understand for know we are tracking the 2.5 dev branch so that its the one that needs to be modified?

The 2.5 dev branch is where the charts for 2.5 live. I'm not sure if things will change for 2.6. We should use this as our starting point.

> I still dont understand why we should link and depend on the rancher featureset that we dont support yet. For now we support name, namespace and dependencies (almost) so why should we test all the rancher custom features???

We don't need to test all of the rancher features. We only need to worry about the things specific to Hypper. This charts repository is just an example for Hypper. So, we can just add our custom annotations in and make sure they are working right. Nothing more is needed.

**Comment by Itxaka** [comment]
I created https://github.com/rancher-sandbox/hypper-charts from rancher charts 2.5 and removed everything that wasnt useful for us (700.000 lines!)

I still dont get this but whatever, its there.

From my point of view, a simple chart repo with the most generic charts used (mysql, wordpress, things like that) with our custom annotations would have been the best approach. That way in the future we can esily show the shared dependencies like 2 WP using the same postgres and so on.


Let me know if this can be closed or we need to expand it further?

**Comment by Itxaka** [comment]
Blocked as awaiting confirmation from @mattfarina that the current implementation is ok!

**Comment by mattfarina** [comment]
> From my point of view, a simple chart repo with the most generic charts used (mysql, wordpress, things like that) with our custom annotations would have been the best approach.

The reason we are starting with the Rancher charts is because:

1. We have a goal of providing the rancher charts as a set of tightly coupled charts that anyone can install. This provides a precurser to those that lets us test this with those charts and provides upgrades to those in the future
2. We can test if our design works for Rancher on the real Rancher charts

**Comment by mattfarina** [comment]
The repository at https://github.com/rancher-sandbox/hypper-charts is missing some element.

It needs to be a helm/hypper repository that can be added with `hypper add charts https://...`. For that to work we need:

- An index.yaml file that has been properly created
- Chart archives for each of the charts that is in a git directory

**Comment by mattfarina** [comment]
For the url for the repository I would expect something like https://rancher-sandbox.github.io/hypper-charts. That would mean the command `hypper repo add hypper-charts https://rancher-sandbox.github.io/hypper-charts` would work. This can be done using GitHub pages.

**Comment by Itxaka** [comment]
You can now add the `https://rancher-sandbox.github.io/hypper-charts/repo` repository to hypper and it works.

unfortunately all versions are devel so they wont show up unless you use the `--devel` flag....

Probably gonna update the charts to make them not devel.

**Comment by Itxaka** [comment]
updated charts to make them non devel so theyc an be installed with `hypper install` 

Tested and works.

To test just run

`hypper repo add hypper https://rancher-sandbox.github.io/hypper-charts/repo`

**Comment by viccuad** [comment]
Nice Itxaka! 

Should we add 1 (fully functional) complex application chart with a couple of shared-deps, for docs? Like, a real app with a database and something else.
At least we could add a simple empty app chart, that depends on several things on the repo.

**Comment by Itxaka** [comment]
yes! That would be great, the point is to keep adding charts when we add features.

**Comment by mattfarina** [comment]
This appears to be done. I've tested charts in it.
